### PR TITLE
Fix INotifyDataErrorInfo Issues on WPF

### PR DESCRIPTION
**Pull request by worldbeater**
**What kind of change does this PR introduce?**

This PR fixes the https://github.com/reactiveui/ReactiveUI.Validation/issues/95 issue.

Also, we are switching to a better solution for https://github.com/reactiveui/ReactiveUI.Validation/issues/31 — we are now using `CurrentThreadScheduler.Instance` as the default scheduler for a `ValidationContext`, because the current implementation of the `ValidationContext` isn't thread-safe anyway, and one can update it only from the main thread (e.g. `BindValidation` currently access the `_validationSource` that is updated via the `ValidationContext.Add` method, and there are no `.ObserveOn(RxApp.MainThreadScheduler)` there). So we expect that a `ValidationContext` is always maintained on the main thread.

**What is the current behavior?**

As described in https://github.com/reactiveui/ReactiveUI.Validation/issues/95, currently, our `INotifyDataErrorInfo` implementation suffers from a couple of issues when used with WPF. One of the issues is described here https://stackoverflow.com/questions/24518520/ui-not-calling-inotifydataerrorinfo-geterrors/24837028#24837028 And another issue is, that WPF expects that we pass the name of the property to the `DataErrorsChangedEventArgs` when raising the `ErrorsChanged` event.

**What is the new behavior?**

Now, we listen to a `IObservable<IChangeSet<IPropertyValidationComponent<TViewModel>>>`, and pass the name of the property associated with a validator to the `ErrorsChanged` event when the state of one of the validators changes. Also, we now update the `HasErrors` property right before a call to `ErrorsChanged` in order to ensure that it contains the correct value. This fixes https://github.com/reactiveui/ReactiveUI.Validation/issues/95 Additionally, we introduce a new `RaiseErrorsChanged(string propertyName)` public API in the `ReactiveValidationObject` class.

**What might this PR break?**

Hopefully nothing.

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

Planning to add some tests soon to ensure we won't break `INotifyDataErrorInfo`-related stuff in the future.

### CODE REVIEW

**Comment by worldbeater** [comment]
Whoops, got a ton of nullability-related warnings 😅 Going to fix that stuff soon as well.

**Review by glennawatson — APPROVED** [review]

**Comment by worldbeater** [comment]
Additionally cherry-picked the updated packages.

**Comment by worldbeater** [comment]
It appears that `ShouldlyConfiguration.DiffTools` is eliminated from `Shoudly` codebase now, according to https://github.com/shouldly/shouldly/blob/a84f7dcb32bdf4e1fa2d2c9ed94dafa4850a5b91/src/Shouldly/Obsoletes.cs#L13. So probably we should adopt the new https://github.com/VerifyTests/DiffEngine

**Comment by worldbeater** [comment]
Fighting with line endings currently.

**Pull request merged**
