### PR TITLE
Fix #60, #61, #70

### LINKED ISSUE #60: [BUG] Validation by property "error sharing" when last property is the same
**Describe the bug**

Using 2 validation rules ending with the same property name, e.g.

```
this.ValidationRule(
            viewModel => viewModel.Origin.Name,
            name => !string.IsNullOrWhiteSpace(name),
            "You must specify a valid origin name");

this.ValidationRule(
            viewModel => viewModel.Destination.Name,
            name => !string.IsNullOrWhiteSpace(name),
            "You must specify a valid destination name");
```

and then

```
this.BindValidation(ViewModel, vm => vm.Origin.Name, view => view.OriginNameError.Text);
this.BindValidation(ViewModel, vm => vm.Destination.Name, view => view.DestinationNameError.Text);
```

results in view.OriginNameError and view.DestinationNameError having *all* "*.Name" errors.

**Steps To Reproduce**

Use example mentioned before.

**Expected behavior**

Errors with the same last property name should not "share" errors.

**Screenshots**

**Environment**

- OS:       Windows / .NET Core 3.0
- Device:   Windows
- Version:   commit aa218ee50bd84a917347e29d2886403fb2dfe9b4
- Working Version: None

but the bug is present on all platforms.

**Additional context**

I have fixed this bug by replacing all instances of "Body.GetMemberInfo().Name" in the code by "Body.GetPropertyPath()", which returns "Origin.Name" and "Destination.Name" instead of only the "Name".

I know you might be in the process of refactoring property validation, but if you are ready, I'll make a pull request.

GetPropertyPath code:

```
// <copyright file="ReactiveUI.Validation/src/ReactiveUI.Validation/Extensions/ExpressionExtensions.cs" company=".NET Foundation">
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// </copyright>

using System.Linq.Expressions;
using System.Text;

namespace ReactiveUI.Validation.Extensions
{
    /// <summary>
    /// Extensions methods associated to <see cref="Expression"/> instances.
    /// </summary>
    public static class ExpressionExtensions
    {
        /// <summary>
        /// Returns a property path expression as a string.
        /// </summary>
        /// <param name="expression">The property path expression.</param>
        /// <returns>The property path string representing the expression.</returns>
        public static string GetPropertyPath(this Expression expression)
        {
            var path = new StringBuilder();
            while (expression is MemberExpression memberExpression)
            {
                if (path.Length > 0)
                    path.Insert(0, '.');

                path.Insert(0, memberExpression.Member.Name);

                expression = memberExpression.Expression;
            }
            return path.ToString();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by worldbeater**
**What kind of change does this PR introduce?**

In this PR, the fixes described in https://github.com/reactiveui/ReactiveUI.Validation/issues/60 and https://github.com/reactiveui/ReactiveUI.Validation/issues/61 were implemented, as well as the test cases for them. Huge thanks to @ins0mniaque for providing these high-quality bug reports and solutions. Also, an extra `.ObserveOn()` added to `this.IsValid()` extension method implementation should resolve https://github.com/reactiveui/ReactiveUI.Validation/issues/70 (for 100% resolution this PR addresses https://github.com/reactiveui/ReactiveUI.Validation/issues/31 as well)

In addition, with this PR we start using `IEnumerable<IValidationComponent>` in `BindValidation` instead of a `ReadOnlyObservableCollection`, based on the information provided in https://github.com/reactiveui/ReactiveUI.Validation/issues/31#issuecomment-574663602. This should finally resolve the issues with `IScheduler`s described in https://github.com/reactiveui/ReactiveUI.Validation/issues/31

**What might this PR break?**

Hopefully nothing.

### CODE REVIEW

**Comment by worldbeater** [comment]
Hmm. Probably we could leave public API as is (`ReadOnlyObservableCollection<T> Validations { get; }`), and introduce an `internal` property which exposes the validations to `BindValidation` without relying on schedulers, that can probably be busy (e.g. `RxApp.MainThreadScheduler` might be busy resolving main thread queue). This way we'd get #31 fixed while preserving API compatibility.

**Comment by glennawatson** [comment]
Do you mind bumping to API generator nuget to latest while here too. Will take care of other outstanding pr

**Comment by worldbeater** [comment]
Going to do it today! Also, will switch from `IReadOnlyCollection` to `IObservableList` as suggested in https://github.com/reactiveui/ReactiveUI.Validation/issues/31#issuecomment-574663602

**Comment by worldbeater** [comment]
Done with upgrading the generator! https://github.com/reactiveui/ReactiveUI.Validation/pull/81

**Pull request merged**
