### PR TITLE
[feature] Clean warnings

### PR DESCRIPTION
**Pull request by alexmartinezm**
Link to issue: https://github.com/reactiveui/ReactiveUI.Validation/issues/10

### CODE REVIEW

**Comment by worldbeater** [comment]
Looks good! By the way seeing a lot of commits unrelated to this particular PR. Those commits seem to be already merged to master, is there any chance to get rid of them?

**Comment by glennawatson** [comment]
I think the fastest way Todo that would be to re clone the repo and paste these changes in from a backup copy.

**Comment by alexmartinezm** [comment]
Those commits are from my last PR, which are not affecting the current PR's goal. So, how should we proceed with this PR now?

**Comment by glennawatson** [comment]
Handling in #13

**Pull request closed without merging**
